# Generated by Django 2.1 on 2018-10-07 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthOrgRelate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('auth_id', models.IntegerField()),
                ('org_id', models.CharField(max_length=32)),
                ('member_id', models.CharField(max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='OrgUserAuth',
        ),
    ]
