# Generated by Django 2.1 on 2018-10-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgauth', '0002_auto_20181007_0358'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgUserAuth',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('member_id', models.CharField(db_index=True, max_length=32)),
                ('org_id', models.CharField(max_length=32)),
                ('passwd', models.CharField(max_length=160)),
                ('org_role', models.CharField(max_length=16)),
            ],
        ),
    ]
