# Generated by Django 2.1 on 2018-10-10 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgauth', '0004_auto_20181007_1345'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthOrgRelate',
        ),
    ]
