# Generated by Django 2.1 on 2018-10-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgBind',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('auth_id', models.IntegerField(db_index=True)),
                ('org_id', models.CharField(db_index=True, max_length=32)),
                ('member_id', models.CharField(db_index=True, max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
