# Generated by Django 2.1 on 2018-10-10 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0005_auto_20181010_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orgbind',
            old_name='auth_id',
            new_name='plat_id',
        ),
    ]
