# Generated by Django 2.1 on 2018-10-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0007_auto_20181010_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgbind',
            name='org_id',
            field=models.CharField(db_index=True, max_length=32),
        ),
    ]
